import type { Metadata } from "next";
import FAQ from "../components/faq";
import TestimonialSection from "../components/testimonials";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <>
        {children}
        <TestimonialSection />
        </>
  );
}
